export const experience = [
  {
    id: "upwork",
    company: "Upwork",
    url: "https://www.upwork.com/freelancers/azadflutterdev",
    role: "Freelance Full-Stack & Mobile Developer",
    period: "Ongoing",
    location: "Remote",
    bullets: [
      "Collaborate with international clients to deliver complete end-to-end products, from mobile apps to web platforms.",
      "Architect and build cross-platform mobile apps using Flutter and React Native.",
      "Develop robust backend systems and APIs using Node.js, Express, and modern databases.",
      "Maintain a 100% Job Success Score through clear communication, reliable delivery, and high code quality.",
    ],
    tech: ["Flutter", "React Native", "React.js", "Node.js", "Firebase", "API Integration"],
    projects: [
      { name: "Yazidi Pro", url: "https://play.google.com/store/apps/details?id=com.yazidi.pro&hl=en" },
      { name: "OldPazar", url: "https://play.google.com/store/apps/details?id=com.flutterdevs.oldpazar&hl=en" },
      { name: "View 30+ Upwork Portfolio Items", url: "https://www.upwork.com/freelancers/azadflutterdev" },
    ]
  },
  {
    id: "codego",
    company: "Codego Group LTD",
    url: "https://codegotech.com/",
    role: "Mobile Application Developer",
    period: "Feb 2024 – Jun 2026",
    location: "Remote · Milan, Italy",
    bullets: [
      "Built and maintained live banking and payment apps for iOS and Android, including CodegoPay, GPTBANQ, and Monnay.",
      "Implemented KYC verification, biometric login, SEPA transfers, and multi-IBAN onboarding.",
      "Developed Flutter apps with Dart, BLoC, Clean Architecture, and reusable components.",
      "Integrated REST APIs for accounts, payments, users, transactions, and notifications.",
      "Used Firebase for push notifications, analytics, crash reporting, and app stability.",
    ],
    tech: ["Flutter", "Dart", "BLoC", "Clean Architecture", "Firebase", "REST APIs", "CI/CD"],
    projects: [
      { name: "Codego Play Store", url: "https://play.google.com/store/apps/developer?id=Codego+Limited" },
      { name: "Coxipay App Store", url: "https://apps.apple.com/il/developer/coxipay/id1681736421" },
      { name: "Coxipay Play Store", url: "https://play.google.com/store/apps/developer?id=Coxipay+LTD" },
      { name: "CodegoTech", url: "https://codegotech.com/" },
      { name: "CDG Project", url: "https://cdgproject.com/" },
      { name: "CoxiWallet", url: "https://coxiwallet.com/" },
    ]
  },
  {
    id: "appdevs",
    company: "AppDevs",
    url: "https://appdevs.net/",
    role: "Senior Software Engineer",
    period: "Feb 2022 – Oct 2023",
    location: "Dhaka, Bangladesh",
    bullets: [
      "Progressed from Intern to Senior Software Engineer, leading a team of 7 Flutter developers.",
      "Developed AdBot, an AI-powered Google Ads automation app using ChatGPT and OpenAI API.",
      "Built and maintained production apps across FinTech, e-commerce, AI, and on-demand services.",
      "Integrated Firebase, REST APIs, Supabase, Unity Ads, and AdMob.",
      "Recognized as Employee of the Month twice in 2022 and 2023.",
    ],
    tech: ["Flutter", "Riverpod", "GetX", "OpenAI API", "Supabase", "AdMob", "Git"],
    projects: [
      { name: "Handiman", url: "https://codecanyon.net/item/handiman-on-demand-services-and-parcel-delivery-platform/51250613" },
      { name: "Escroc", url: "https://codecanyon.net/item/escroc-money-transfer-with-escrow-full-solution/49645580" },
      { name: "Xremit Pro", url: "https://codecanyon.net/item/xremit-pro-remittance-money-transfer-solution/48035206" },
      { name: "GameShop", url: "https://codecanyon.net/item/gameshop-game-topup-diamond-and-coin-selling-business-platform/48224092" },
      { name: "StripCard", url: "https://codecanyon.net/item/stripcard-virtual-credit-card-solution/47909310" },
      { name: "AdChange P2P", url: "https://codecanyon.net/item/adchange-p2p-trading-platform-full-solution/47643709" },
      { name: "CrypInvest", url: "https://codecanyon.net/item/crypinvest-cryptocurrency-investment-platform-full-solution/47446877" },
      { name: "SuperVPN", url: "https://codecanyon.net/item/supervpn-unlimited-free-vpn-flutter-app/47643145" },
      { name: "eFunding", url: "https://codecanyon.net/item/efunding-crowdfunding-platform-android-and-ios-app-website-admin-panel/46864399" },
      { name: "TikTokShop", url: "https://codecanyon.net/item/tiktokshop-buy-and-sell-tiktok-coin-business-full-solution/46378086" },
      { name: "AdBot Pro", url: "https://codecanyon.net/item/adbotpro-chatgpt-business-platform-website-androidios-app-admin-panel/45299173" },
      { name: "AdFund", url: "https://codecanyon.net/item/adfund-fund-raising-platform-website-androidios-app-admin-panel/45306012" },
      { name: "AdBot AI", url: "https://codecanyon.net/item/adbot-chatgpt-open-ai-android-and-ios-app/43160720" },
      { name: "Xremit", url: "https://codecanyon.net/item/xremit-remittance-solutions-money-transfer-flutter-app/40451218" },
      { name: "XTrading", url: "https://codecanyon.net/item/xtrading-online-trading-and-investment-platform-flutter-app/40371860" },
      { name: "SMMHub", url: "https://codecanyon.net/item/smmhub-social-media-marketing-flutter-app/40025453" },
      { name: "OneRadio", url: "https://codecanyon.net/item/oneradio-online-radio-streaming-app-with-admob-in-android-and-ios/38689750" },
      { name: "Walletium", url: "https://codecanyon.net/item/walletium-advanced-digital-mobile-wallet-flutter-app/38183039" },
      { name: "xPay", url: "https://codecanyon.net/item/xpay-mobile-banking-e-wallet-flutter-app/37419851" },
      { name: "CrypInvest UI Kit", url: "https://codecanyon.net/item/crypinvest-cryptocurrency-investment-platform-flutter-app-ui-kit/37184257" },
    ]
  },
  {
    id: "divine-it",
    company: "Divine IT Limited",
    url: "https://www.divineit.net/",
    role: "Software Engineer Intern",
    period: "Oct 2021 – Jan 2022",
    location: "Dhaka, Bangladesh",
    bullets: [
      "Gained practical experience in full-stack application development using Flutter and Python Django.",
      "Developed frontend screens, UI components, and used state management (BLoC, Provider, Riverpod).",
      "Connected mobile app features with backend APIs and databases.",
    ],
    tech: ["Flutter", "Dart", "Python Django", "PostgreSQL", "Provider", "REST APIs"],
  },
];

export type Experience = (typeof experience)[number];
