import { Project } from "@/lib/types";

export const portfolioProjects: Project[] = [
  {
    id: "p1",
    title: "CodegoPay Individual",
    slug: "codegopay-individual",
    role: "Full Stack Flutter Developer",
    description:
      "Personal banking app for European IBAN onboarding, SEPA transfers, biometric authorization, and account management.",
    details:
      "Built from Codego public product data and official website assets. Project centers on personal banking flows: European IBAN setup, SEPA and SEPA Instant transfers, direct debit support, biometric payment authorization, and always-on account access.",
    images: [
      "https://codegopay.com/1.png",
    ],
    techStack: ["Flutter", "Dart", "REST API", "Biometric Auth", "SEPA", "Apple Pay"],
    features: [
      "European IBAN onboarding",
      "SEPA and SEPA Instant transfers",
      "Biometric payment authorization",
      "Direct debit support",
      "Budgeting and account access flows",
    ],
    links: {
      playStore: "https://play.google.com/store/apps/details?id=com.codegopay.individual",
      appStore: "https://apps.apple.com/ie/app/codegopay-individual/id6478804402",
      website: "https://codegopay.com/",
    },
    featured: true,
  },
  {
    id: "p2",
    title: "CodegoPay Business",
    slug: "codegopay-business",
    role: "Flutter Developer",
    description:
      "Business banking platform focused on fast onboarding, dedicated IBAN accounts, and SEPA payment operations.",
    details:
      "Built from Codego business website content and live store listing. Product highlights business onboarding in under 10 minutes, dedicated IBAN accounts, instant SEPA payments, and finance management for companies from single dashboard.",
    images: [
      "https://res.cloudinary.com/hashfort/image/upload/v1683010927/pagecontent/ht0epy9iasqd66a3vn6p.png",
    ],
    techStack: ["Flutter", "Dart", "REST API", "KYC", "SEPA", "Business Banking"],
    features: [
      "Business account onboarding",
      "Dedicated IBAN accounts",
      "SEPA and SEPA Instant payments",
      "Document upload and identity verification",
      "Dashboard-driven finance management",
    ],
    links: {
      playStore: "https://play.google.com/store/apps/details?id=code.gopay.business",
      appStore: "https://apps.apple.com/ie/app/codegopay-business/id6478826879",
      website: "https://business.codegopay.com/",
    },
    featured: true,
  },
  {
    id: "p3",
    title: "FiberVPN",
    slug: "fibervpn",
    description:
      "VPN app with country selection, connection state, premium plan prompts, and payment-ready upgrade flow.",
    details:
      "Based on provided portfolio assets and Codego public store listing. Screens show live connection state, location switching, premium upsell, and secure network access flow across mobile devices.",
    images: [
      "/project-assets/vpn/1.png",
      "/project-assets/vpn/2.png",
    ],
    techStack: ["Flutter", "Dart", "Laravel", "REST API", "Payments", "Subscriptions"],
    features: [
      "VPN connect and disconnect state",
      "Country and city selection",
      "Premium upgrade flow",
      "Cross-platform mobile support",
      "Payment-ready subscription UI",
    ],
    links: {
      playStore: "https://play.google.com/store/apps/details?id=com.codego.fibervpns",
      appStore: "https://apps.apple.com/ie/app/fibervpn/id6755590267",
    },
    featured: true,
  },
  {
    id: "p4",
    title: "NXFund",
    slug: "nxfund",
    role: "Full Stack Flutter Developer",
    description:
      "Fundraising platform with wallet, payment flows, donation actions, and campaign-first experience.",
    details:
      "Built with Flutter and Laravel stack for donation workflows, wallet actions, and campaign management. Product supports responsive mobile and larger-screen layout patterns for funding visibility.",
    images: [
      "/project-assets/nxfund/0.jpg",
      "/project-assets/nxfund/1.jpg",
      "/project-assets/nxfund/2.jpg",
      "/project-assets/nxfund/3.jpg",
      "/project-assets/nxfund/4.jpg",
    ],
    techStack: ["Flutter", "Laravel", "Wallet", "Payments", "Fundraising"],
    features: [
      "Campaign discovery",
      "Donation and checkout flow",
      "Wallet interactions",
      "Campaign detail breakdown",
      "Responsive fundraising layout",
    ],
    links: {},
    featured: true,
  },
  {
    id: "p5",
    title: "E-commerce App (Flutter + Laravel)",
    slug: "nxmart",
    role: "Full Stack Flutter Developer",
    description:
      "Full commerce app with product discovery, cart flow, checkout, and payment handling.",
    details:
      "Built with Flutter frontend and Laravel backend integration. Product includes catalog browsing, product details, add-to-cart behavior, checkout states, and order-focused payment screens.",
    images: [
      "/project-assets/nxmart/Promo%201.jpg",
      "/project-assets/nxmart/Promo%202.jpg",
      "/project-assets/nxmart/Promo%203.jpg",
      "/project-assets/nxmart/Promo%204.jpg",
      "/project-assets/nxmart/Promo%205.jpg",
      "/project-assets/nxmart/Promo%206.jpg",
      "/project-assets/nxmart/Promo%207.jpg",
      "/project-assets/nxmart/Promo%208.jpg",
      "/project-assets/nxmart/Promo%209.jpg",
    ],
    techStack: ["Flutter", "Laravel", "E-commerce", "Cart", "Payments"],
    features: [
      "Product search",
      "Category navigation",
      "Product detail views",
      "Cart and checkout",
      "Multiple payment method UI",
    ],
    links: {},
    featured: true,
  },
  {
    id: "p6",
    title: "NexoPay - FinTech Wallet & Crypto App",
    slug: "nexopay",
    role: "Full Stack Flutter Developer",
    description:
      "Wallet and crypto product with transfers, invoices, multi-currency support, and account dashboards.",
    details:
      "End-to-end Flutter implementation for fintech and crypto user journeys. Product includes transaction workflows, invoice actions, currency handling, and clean wallet dashboard navigation.",
    images: [
      "/project-assets/nexopay/1.jpg",
      "/project-assets/nexopay/2.jpg",
      "/project-assets/nexopay/3.jpg",
    ],
    techStack: ["Flutter", "Laravel", "Wallet", "Crypto", "Multi-currency"],
    features: [
      "Wallet dashboard",
      "Crypto and transfer flows",
      "Invoice actions",
      "Multi-currency support",
      "Finance account management",
    ],
    links: {},
    featured: true,
  },
  {
    id: "p7",
    title: "AI Study Planner (Flutter + Firebase + ChatGPT)",
    slug: "studygenie-ai",
    role: "Flutter Developer",
    description:
      "AI learning assistant with chat support, flashcards, quizzes, and progress planning.",
    details:
      "Flutter app connected to Firebase services and ChatGPT-powered study interactions. Student workflow covers AI chat help, flashcard practice, quiz rounds, and progress tracking dashboards.",
    images: [
      "/project-assets/studygenie-ai/1.png",
      "/project-assets/studygenie-ai/2.png",
      "/project-assets/studygenie-ai/3.png",
    ],
    techStack: ["Flutter", "Firebase", "ChatGPT", "AI Chat", "EdTech"],
    features: [
      "Structured study notes",
      "AI summaries",
      "Flashcard generation",
      "Quiz assistance",
      "Progress tracking",
    ],
    links: {},
    featured: true,
  },
  {
    id: "p8",
    title: "Fitness & Running Tracker",
    slug: "runava",
    role: "Flutter Developer",
    description:
      "Running and fitness app for activity tracking, challenges, event discovery, and ticket booking.",
    details:
      "Based on provided Runava assets. Screens show challenge feed, step and calorie stats, event details, race ticket purchase, and community-style run organization flows.",
    images: [
      "/project-assets/runava/1.jpg",
      "/project-assets/runava/2.jpg",
      "/project-assets/runava/3.jpg",
      "/project-assets/runava/4.jpg",
    ],
    techStack: ["Flutter", "GPS Tracking", "Social Features", "Events", "Fitness"],
    features: [
      "Run activity metrics",
      "Challenges and streaks",
      "Event listing",
      "Race ticket booking",
      "Club and organizer views",
    ],
    links: {},
    featured: false,
  },
  {
    id: "p9",
    title: "NexGro",
    slug: "nexgro",
    role: "Flutter Developer",
    description:
      "Agri-investment product with farm listings, expected returns, tenure filters, and project purchase flow.",
    details:
      "Based on provided NexGro assets. Interface shows agricultural projects with unit pricing, return ranges, duration, location, and booking actions for investment-style farm products.",
    images: [
      "/project-assets/nexgro/1.png",
      "/project-assets/nexgro/2.png",
    ],
    techStack: ["Flutter", "Agri FinTech", "Investment Tracking", "Payments", "Dashboards"],
    features: [
      "Farm listing cards",
      "Return and duration filters",
      "Project detail breakdown",
      "Booking flow",
      "Portfolio-style browsing",
    ],
    links: {},
    featured: true,
  },
  {
    id: "p11",
    title: "Ummah Charity Platform",
    slug: "ummah-charity",
    role: "Full Stack Flutter Developer",
    description:
      "Faith and community app combining Quran reading, translated surahs, social feed, and charity-oriented interactions.",
    details:
      "Based on provided Ummah Charity assets. Product blends Quran reading interfaces with community activity feed, comments, and charity-oriented user engagement flows.",
    images: [
      "/project-assets/ummah-charity/1.png",
      "/project-assets/ummah-charity/2.png",
      "/project-assets/ummah-charity/3.png",
      "/project-assets/ummah-charity/4.png",
      "/project-assets/ummah-charity/7.jpg",
      "/project-assets/ummah-charity/8.jpg",
      "/project-assets/ummah-charity/9.jpg",
    ],
    techStack: ["Flutter", "Laravel", "Donations", "Payments", "Community"],
    features: [
      "Surah browsing",
      "Reading screen with translations",
      "Bookmarks and playback controls",
      "Community feed",
      "Comment engagement",
    ],
    links: {},
    featured: true,
  },
  {
    id: "p12",
    title: "Chat Application (Flutter + Firebase)",
    slug: "kream-suger",
    role: "Flutter Developer",
    description:
      "Realtime chat-style social app with authentication and user interaction flows.",
    details:
      "Built with Flutter and Firebase patterns for realtime messaging experiences. Product assets highlight user presence, profile interactions, and communication-oriented engagement flow.",
    images: [
      "/project-assets/kream-suger/1.jpg",
      "/project-assets/kream-suger/2.jpg",
      "/project-assets/kream-suger/3.jpg",
    ],
    techStack: ["Flutter", "Firebase", "Realtime Chat", "Authentication", "Social UI"],
    features: [
      "Realtime interaction flow",
      "User authentication patterns",
      "Social profile views",
      "Message-ready UI states",
    ],
    links: {},
    featured: false,
  },
  {
    id: "p13",
    title: "Nexflix",
    slug: "nexflix",
    role: "Flutter Developer",
    description:
      "Entertainment app concept with poster-driven browsing, movie detail screens, and media discovery layouts.",
    details:
      "Combined Nexflix project entry based on provided assets. Focus on media discovery patterns with hero posters, trending collections, movie detail CTA, and polished entertainment browsing flow.",
    images: [
      "/project-assets/nexflix-latest/2015.jpg",
      "/project-assets/nexflix-latest/2016.jpg",
      "/project-assets/nexflix-latest/2017.jpg",
      "/project-assets/nexflix-latest/2018.jpg",
      "/project-assets/nexflix-latest/2019.jpg",
      "/project-assets/nexflix-latest/2020.jpg",
      "/project-assets/nexflix-latest/2021.jpg",
      "/project-assets/nexflix-old/M1.jpg",
      "/project-assets/nexflix-old/M2.jpg",
    ],
    techStack: ["Flutter", "Dart", "Video UI", "Media Discovery"],
    features: [
      "Trending media feed",
      "Poster-based browsing",
      "Movie detail CTA",
      "Collections and account tabs",
    ],
    links: {},
    featured: false,
  },
  {
    id: "p10",
    title: "Food Delivery App",
    slug: "nexo-mart",
    role: "Flutter Developer",
    description:
      "Food ordering app with discovery, cart, checkout, and social-style engagement patterns.",
    details:
      "Built from provided product assets to cover mobile-first ordering flow, item browsing, checkout decisions, and interaction-focused user journey for delivery use cases.",
    images: [
      "/project-assets/nexo-mart/1.png",
      "/project-assets/nexo-mart/2.png",
    ],
    techStack: ["Flutter", "Ordering Flow", "Checkout", "Payments", "Social Features"],
    features: [
      "Menu and item browsing",
      "Cart and order actions",
      "Checkout decisions",
      "Delivery-oriented navigation",
      "Engagement-focused UI",
    ],
    links: {},
    featured: false,
  },
  {
    id: "p15",
    title: "CoxiPay Individual",
    slug: "coxipay-individual",
    role: "Flutter Developer",
    description: "Fintech mobile app entry sourced from public Play Store listing.",
    details: "Project listing based on provided Play Store package link for CoxiPay Individual.",
    images: ["/project-assets/codegopay-individual/website-section.png"],
    techStack: ["Flutter", "Dart", "REST API", "FinTech", "Payments"],
    features: ["Play Store published app", "Mobile onboarding flow", "Transaction-ready experience"],
    links: {
      playStore: "https://play.google.com/store/apps/details?id=coxi.pay.individual",
    },
    featured: false,
  },
  {
    id: "p16",
    title: "CoxiPay Business",
    slug: "coxipay-business",
    role: "Flutter Developer",
    description: "Business fintech app entry sourced from public Play Store listing.",
    details: "Project listing based on provided Play Store package link for CoxiPay Business.",
    images: ["/project-assets/codegopay-business/website-section.png"],
    techStack: ["Flutter", "Dart", "REST API", "FinTech", "Business Payments"],
    features: ["Play Store published app", "Business account workflows", "Finance operations UI"],
    links: {
      playStore: "https://play.google.com/store/apps/details?id=coxipay.app.business",
    },
    featured: false,
  },
  {
    id: "p17",
    title: "Banqa Pay",
    slug: "banqa-pay",
    role: "Flutter Developer",
    description: "Consumer payments app entry sourced from Play Store listing.",
    details: "Project listing based on provided Play Store package link for Banqa Pay.",
    images: ["/project-assets/nexopay/1.jpg"],
    techStack: ["Flutter", "Dart", "FinTech", "Wallet", "Payments"],
    features: ["Play Store published app", "Wallet-focused flow", "Consumer payment UX"],
    links: {
      playStore: "https://play.google.com/store/apps/details?id=pay.banqa.io",
    },
    featured: false,
  },
  {
    id: "p18",
    title: "Banqa Business",
    slug: "banqa-business",
    role: "Flutter Developer",
    description: "Business finance app entry sourced from Play Store listing.",
    details: "Project listing based on provided Play Store package link for Banqa Business.",
    images: ["/project-assets/nexopay/2.jpg"],
    techStack: ["Flutter", "Dart", "FinTech", "Business", "Payments"],
    features: ["Play Store published app", "Business payment support", "Account workflow UX"],
    links: {
      playStore: "https://play.google.com/store/apps/details?id=com.banqa.business",
    },
    featured: false,
  },
  {
    id: "p19",
    title: "Codego KYC Individual",
    slug: "codego-kyc-individual",
    role: "Flutter Developer",
    description: "KYC-focused fintech app entry sourced from Play Store listing.",
    details: "Project listing based on provided Play Store package link for Codego KYC Individual.",
    images: ["/project-assets/codegopay-individual/website-section.png"],
    techStack: ["Flutter", "Dart", "KYC", "FinTech", "Identity Verification"],
    features: ["Play Store published app", "KYC process support", "Identity workflow UI"],
    links: {
      playStore: "https://play.google.com/store/apps/details?id=com.codegokyc.individual",
    },
    featured: false,
  },
  {
    id: "p20",
    title: "Orbyx Business",
    slug: "orbyx-business",
    role: "Flutter Developer",
    description: "Business banking app entry sourced from Play Store listing.",
    details: "Project listing based on provided Play Store package link for Orbyx Business.",
    images: ["/project-assets/codegopay-business/website-section.png"],
    techStack: ["Flutter", "Dart", "FinTech", "Business Banking", "Payments"],
    features: ["Play Store published app", "Business banking UX", "Transaction-oriented flow"],
    links: {
      playStore: "https://play.google.com/store/apps/details?id=orbyx.business.app",
    },
    featured: false,
  },
  {
    id: "p21",
    title: "GPTBanq Business",
    slug: "gptbanq-business",
    role: "Flutter Developer",
    description: "Business fintech app entry sourced from Play Store listing.",
    details: "Project listing based on provided Play Store package link for GPTBanq Business.",
    images: ["/project-assets/codegopay-business/website-section.png"],
    techStack: ["Flutter", "Dart", "FinTech", "Business", "Payments"],
    features: ["Play Store published app", "Business finance workflow", "Mobile transaction UX"],
    links: {
      playStore: "https://play.google.com/store/apps/details?id=com.gptbanq.business",
    },
    featured: false,
  },
  {
    id: "p22",
    title: "CDG Pro",
    slug: "cdg-pro",
    role: "Flutter Developer",
    description: "Professional fintech app entry sourced from Play Store listing.",
    details: "Project listing based on provided Play Store package link for CDG Pro.",
    images: ["/project-assets/codegopay-business/website-section.png"],
    techStack: ["Flutter", "Dart", "FinTech", "Payments", "Business Tools"],
    features: ["Play Store published app", "Professional user workflow", "Finance operation UI"],
    links: {
      playStore: "https://play.google.com/store/apps/details?id=com.cdg.pro",
    },
    featured: false,
  },
  {
    id: "p23",
    title: "Orbyx Individual",
    slug: "orbyx-individual",
    role: "Flutter Developer",
    description: "Consumer fintech app entry sourced from Play Store listing.",
    details: "Project listing based on provided Play Store package link for Orbyx Individual.",
    images: ["/project-assets/codegopay-individual/website-section.png"],
    techStack: ["Flutter", "Dart", "FinTech", "Wallet", "Payments"],
    features: ["Play Store published app", "Individual account flow", "Consumer payment UX"],
    links: {
      playStore: "https://play.google.com/store/apps/details?id=com.orbyx.individual",
    },
    featured: false,
  },
  {
    id: "p24",
    title: "GPTBanq Individual",
    slug: "gptbanq-individual",
    role: "Flutter Developer",
    description: "Consumer fintech app entry sourced from Play Store listing.",
    details: "Project listing based on provided Play Store package link for GPTBanq Individual.",
    images: ["/project-assets/codegopay-individual/website-section.png"],
    techStack: ["Flutter", "Dart", "FinTech", "Wallet", "Payments"],
    features: ["Play Store published app", "Personal finance workflows", "Mobile payment experience"],
    links: {
      playStore: "https://play.google.com/store/apps/details?id=com.gptbanq.individual",
    },
    featured: false,
  },
];
